version: '3.8'

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: kontrolla-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-KontrollaPro2024!Secure}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-kontrollapro}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/src/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./Backend/src/database/seed.js:/docker-entrypoint-initdb.d/02-seed.js
    networks:
      - kontrolla-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s

  # Backend Node.js
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: kontrolla-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-kontrollapro}
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-KontrollaPro2024!Secure}
      JWT_SECRET: ${JWT_SECRET:-KontrollaPro_JWT_Secret_2024_Ultra_Secure_Key_Production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      CORS_ORIGIN: ${CORS_ORIGIN:-https://seudominio.com}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    ports:
      - "3000:3000"
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./certificados:/app/certificados
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - kontrolla-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend React com Nginx
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: kontrolla-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - backend
    networks:
      - kontrolla-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis para cache e sessões
  redis:
    image: redis:7-alpine
    container_name: kontrolla-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kontrolla-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-KontrollaPro2024!Redis}

  # Nginx como proxy reverso (opcional, se não usar o nginx do frontend)
  nginx:
    image: nginx:alpine
    container_name: kontrolla-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - kontrolla-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  kontrolla-network:
    driver: bridge
