services:
  mysql:
    image: mysql:8.0
    container_name: kontrolla-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - kontrolla-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kontrolla-redis
    restart: unless-stopped
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kontrolla-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 10s
      retries: 3

  backend:
    build: ./Backend
    container_name: kontrolla-backend
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - kontrolla-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_APP_URL=${VITE_APP_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_NODE_ENV=${VITE_NODE_ENV}
        - VITE_APP_NAME=${VITE_APP_NAME}
        - VITE_APP_VERSION=${VITE_APP_VERSION}
        - VITE_ENABLE_ANALYTICS=${VITE_ENABLE_ANALYTICS}
        - VITE_ENABLE_ERROR_REPORTING=${VITE_ENABLE_ERROR_REPORTING}
        - VITE_ENABLE_PERFORMANCE_MONITORING=${VITE_ENABLE_PERFORMANCE_MONITORING}
        - VITE_CACHE_ENABLED=${VITE_CACHE_ENABLED}
        - VITE_CACHE_TTL=${VITE_CACHE_TTL}
        - VITE_MAX_FILE_SIZE=${VITE_MAX_FILE_SIZE}
        - VITE_ALLOWED_FILE_TYPES=${VITE_ALLOWED_FILE_TYPES}
        - VITE_SECURE_COOKIES=${VITE_SECURE_COOKIES}
        - VITE_SAME_SITE=${VITE_SAME_SITE}
    container_name: kontrolla-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - kontrolla-network
    depends_on:
      - backend

networks:
  kontrolla-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: